AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CFInvalidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.cf_invalidator
      Runtime: python3.9
  CFShowDistributionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.cf_distributions
      Runtime: python3.9
