AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 10
Resources:
  CFInvalidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.invalidation
      Runtime: python3.9
      Policies:
        - arn:aws:iam::069889557760:policy/gx-bot
  CFShowDistributionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.distributions
      Runtime: python3.9
      Environment:
        Variables:
          DISTRIBUTIONS: "E2YOAZP0AV74Z0,E2YF41IFAE1JFI"
      Policies:
        - arn:aws:iam::069889557760:policy/gx-bot